# ---------------------------------------------------------------------------
# Bedrock GitHub Actions CI build on Windows.
# ---------------------------------------------------------------------------

name: CI Build (Win)

on:
  workflow_dispatch:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        module:
          - bedrock-core
          - bedrock-runtime
          - bedrock-runtime-windows-tests

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 21

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build
      shell: bash
      run: |
        export DEV_ROOT=$(pwd)
        mvn -U --batch-mode -e clean install -DskipTests -Pcoherence-ce
        mvn --batch-mode -e -nsu verify -pl ${{ matrix.module }} -Pcoherence-ce -Dgithub.build=true
