# ---------------------------------------------------------------------------
# Bedrock dependencies check.
# ---------------------------------------------------------------------------

name: Dependencies Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 21

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Check
      shell: bash
      run: |
        export MAVEN_ARGS="-P coherence-ce"
        sh ./etc/dependency-check.sh

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: build-output
        path: "target/*.*"
